# Generated by Django 4.2.19 on 2025-03-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikName', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('nikName',),
            },
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('priority', models.IntegerField()),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trackFileURL', models.TextField()),
                ('pointList', models.TextField()),
                ('length', models.IntegerField()),
                ('startDateTime', models.DateTimeField()),
                ('startPlace', models.TextField()),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author')),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.complexity')),
            ],
            options={
                'ordering': ('-startDateTime',),
            },
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('priority', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trackFileURL', models.TextField()),
                ('pointList', models.TextField()),
                ('photoURL', models.TextField()),
                ('length', models.IntegerField()),
                ('asphalt', models.IntegerField()),
                ('grader', models.IntegerField()),
                ('soil', models.IntegerField()),
                ('jungle', models.IntegerField()),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author')),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.complexity')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('photoURL', models.TextField()),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.event')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.route')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.route'),
        ),
        migrations.AddField(
            model_name='event',
            name='tempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tempo'),
        ),
        migrations.AddField(
            model_name='event',
            name='typeEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeevent'),
        ),
    ]
