# Generated by Django 4.2.19 on 2025-03-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_photourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('ip', models.IntegerField(verbose_name='ip-адрес')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('nikName',), 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='complexity',
            options={'ordering': ('priority',), 'verbose_name': 'Сложность маршрута', 'verbose_name_plural': 'Сложности маршрута'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-startDateTime',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date',), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('name',), 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='tempo',
            options={'ordering': ('priority',), 'verbose_name': 'Темп', 'verbose_name_plural': 'Темпы'},
        ),
        migrations.AlterModelOptions(
            name='typeevent',
            options={'ordering': ('name',), 'verbose_name': 'Тип события', 'verbose_name_plural': 'Типы событий'},
        ),
        migrations.AlterField(
            model_name='author',
            name='nikName',
            field=models.CharField(max_length=15, verbose_name='NikName'),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='complexity',
            name='priority',
            field=models.IntegerField(verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.complexity', verbose_name='Сложность маршрута'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='length',
            field=models.IntegerField(verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photoURL',
            field=models.TextField(default='', verbose_name='Ссылка на фотографию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pointList',
            field=models.TextField(verbose_name='Нитка маршрута'),
        ),
        migrations.AlterField(
            model_name='event',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDateTime',
            field=models.DateTimeField(verbose_name='Дата и время старта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startPlace',
            field=models.TextField(verbose_name='Место старта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tempo', verbose_name='Темп'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trackFileURL',
            field=models.TextField(verbose_name='Ссылка на файл с треком'),
        ),
        migrations.AlterField(
            model_name='event',
            name='typeEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeevent', verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(verbose_name='Содержимое отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Дата поездки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='report',
            name='photoURL',
            field=models.TextField(verbose_name='Ссылка на фотографию'),
        ),
        migrations.AlterField(
            model_name='report',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='route',
            name='asphalt',
            field=models.IntegerField(verbose_name='Асфальт'),
        ),
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='route',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.complexity', verbose_name='Сложность маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='grader',
            field=models.IntegerField(verbose_name='Грейдер'),
        ),
        migrations.AlterField(
            model_name='route',
            name='jungle',
            field=models.IntegerField(verbose_name='Дебри'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='route',
            name='photoURL',
            field=models.TextField(verbose_name='Ссылка на фотографию'),
        ),
        migrations.AlterField(
            model_name='route',
            name='pointList',
            field=models.TextField(verbose_name='Нитка маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='soil',
            field=models.IntegerField(verbose_name='Грунт'),
        ),
        migrations.AlterField(
            model_name='route',
            name='trackFileURL',
            field=models.TextField(verbose_name='Ссылка на файл с треком'),
        ),
        migrations.AlterField(
            model_name='tempo',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='tempo',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tempo',
            name='priority',
            field=models.IntegerField(verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='typeevent',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
    ]
