# Generated by Django 4.2.19 on 2025-03-25 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visitcount_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateCreate',
            field=models.DateField(default=datetime.date(2025, 3, 25), verbose_name='Дата создания события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dateUpdate',
            field=models.DateField(default=datetime.date(2025, 3, 25), verbose_name='Дата обновления события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='dateCreate',
            field=models.DateField(default=datetime.date(2025, 3, 25), verbose_name='Дата создания отчета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='dateUpdate',
            field=models.DateField(default=datetime.date(2025, 3, 25), verbose_name='Дата обновления отчета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='dateCreate',
            field=models.DateField(default=datetime.date(2025, 3, 25), verbose_name='Дата создания маршрута'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='dateUpdate',
            field=models.DateField(default=datetime.date(2025, 3, 25), verbose_name='Дата обновления маршрута'),
            preserve_default=False,
        ),
    ]
