# Generated by Django 4.2.19 on 2025-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_datecreate_event_dateupdate_report_datecreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcount',
            name='ip',
            field=models.PositiveIntegerField(verbose_name='ip-адрес'),
        ),
    ]
