# Generated by Django 4.2.19 on 2025-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_visitcount_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcount',
            name='ip',
            field=models.PositiveBigIntegerField(verbose_name='ip-адрес'),
        ),
    ]
