# Generated by Django 4.2.19 on 2025-03-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_visitcount_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Статус события'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Статус отчета'),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Статус маршрута'),
        ),
    ]
