# Generated by Django 4.2.19 on 2025-07-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_status_report_status_route_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeModule', models.IntegerField(verbose_name='Тип модуля')),
                ('idPage', models.IntegerField(verbose_name='Идентификатор страницы в модуле')),
                ('count', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
            },
        ),
    ]
