# Generated by Django 4.2.19 on 2025-09-05 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='datelast',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата последнего просмотра'),
        ),
    ]
