# Generated by Django 4.2.19 on 2026-01-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_viewcount_datelast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trackFileURL',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на файл с треком'),
        ),
    ]
