# Generated by Django 4.2.19 on 2026-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_trackfileurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Содержимое сообщения')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('dateCreate', models.DateField(verbose_name='Дата создания сообщения')),
                ('dateUpdate', models.DateField(verbose_name='Дата обновления сообщения')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='Статус сообщения')),
            ],
        ),
    ]
