# Generated by Django 4.2.19 on 2026-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('-priority', '-dateCreate'), 'verbose_name': 'Информационное сообщение', 'verbose_name_plural': 'Информационные сообщения'},
        ),
        migrations.AddField(
            model_name='event',
            name='miniReport',
            field=models.TextField(blank=True, null=True, verbose_name='Миниотчет'),
        ),
    ]
